<?php $_slides = $this->getDataFromTable(); ?>
<?php $_helper = Mage::helper('itdelight_examination'); ?>

<div class="container">
    <div id="cbp-fwslider" class="cbp-fwslider">
        <ul>
            <?php if (empty($_slides->getSize())): ?>
                <?php
                $html = '<li><a href="#"><img src="'. $this->getSkinUrl("full_width_image_slider/images/1.jpg") . '" alt="img01"/></a></li>';
                $html.= '<li><a href="#"><img src="'. $this->getSkinUrl("full_width_image_slider/images/2.jpg") . '" alt="img01"/></a></li>';
                $html.= '<li><a href="#"><img src="'. $this->getSkinUrl("full_width_image_slider/images/3.jpg") . '" alt="img01"/></a></li>';
                echo $html;
                ?>
            <?php else: ?>
                <?php foreach ($_slides as $slide): ?>
                    <li>
                        <a href="#">
                            <img src="<?php echo $_helper->getImageUrl() . $slide->getImage(); ?>" alt="<?php echo $slide->getTitle(); ?>"/>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </div>
</div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="<?php echo $this->getSkinUrl("full_width_image_slider/js/jquery.cbpFWSlider.min.js") ?>"></script>
<script>
    $( function() {
        /*
         - how to call the plugin:
         $( selector ).cbpFWSlider( [options] );
         - options:
         {
         // default transition speed (ms)
         speed : 500,
         // default transition easing
         easing : 'ease'
         }
         - destroy:
         $( selector ).cbpFWSlider( 'destroy' );
         */

        $( '#cbp-fwslider' ).cbpFWSlider();

    } );
</script>
