<?php $_slides = $this->getDataFromTable(); ?>
<?php $_helper = Mage::helper('itdelight_examination'); ?>

<div class="container">
    <div id="cbp-fwslider" class="cbp-fwslider">
        <ul>
            <?php foreach ($_slides as $slide): ?>
                <!--    --><?php //Zend_Debug::dump($slide); die;?>
                <li>
                    <a href="#">
                        <img src="<?php echo $_helper->getImageUrl() . $slide->getImage(); ?>" alt="<?php echo $slide->getTitle(); ?>"/>
                    </a>
                </li>
            <?php endforeach; ?>
            <li><a href="#"><img src="<?php echo $this->getSkinUrl("full_width_image_slider/images/1.jpg") ?>" alt="img01"/></a></li>
            <li><a href="#"><img src="<?php echo $this->getSkinUrl("full_width_image_slider/images/2.jpg") ?>" alt="img02"/></a></li>
            <li><a href="#"><img src="<?php echo $this->getSkinUrl("full_width_image_slider/images/3.jpg") ?>" alt="img03"/></a></li>
            <li><a href="#"><img src="<?php echo $this->getSkinUrl("full_width_image_slider/images/4.jpg") ?>" alt="img04"/></a></li>
            <li><a href="#"><img src="<?php echo $this->getSkinUrl("full_width_image_slider/images/5.jpg") ?>" alt="img05"/></a></li>
        </ul>
    </div>
</div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="<?php echo $this->getSkinUrl("full_width_image_slider/js/jquery.cbpFWSlider.min.js") ?>"></script>
<script>
    $( function() {
        /*
         - how to call the plugin:
         $( selector ).cbpFWSlider( [options] );
         - options:
         {
         // default transition speed (ms)
         speed : 500,
         // default transition easing
         easing : 'ease'
         }
         - destroy:
         $( selector ).cbpFWSlider( 'destroy' );
         */

        $( '#cbp-fwslider' ).cbpFWSlider();

    } );
</script>
